// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC20ciN4QE33c6KUQ7XQphkAZnTOBlGp4I',
    appId: '1:999477299207:web:ad6025088b3d09495a82a2',
    messagingSenderId: '999477299207',
    projectId: 'connect-call-e0fc2',
    authDomain: 'connect-call-e0fc2.firebaseapp.com',
    storageBucket: 'connect-call-e0fc2.firebasestorage.app',
    measurementId: 'G-TP25Q308E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6IcbQnEN5Ofcbxz4y2BZhR0H-CQJlTqA',
    appId: '1:999477299207:android:5677afdda6536e495a82a2',
    messagingSenderId: '999477299207',
    projectId: 'connect-call-e0fc2',
    storageBucket: 'connect-call-e0fc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxNm1mXEY85mMvGiYlgvFxZh9WPbLg6PA',
    appId: '1:999477299207:ios:dec19cb9dcad091d5a82a2',
    messagingSenderId: '999477299207',
    projectId: 'connect-call-e0fc2',
    storageBucket: 'connect-call-e0fc2.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxNm1mXEY85mMvGiYlgvFxZh9WPbLg6PA',
    appId: '1:999477299207:ios:dec19cb9dcad091d5a82a2',
    messagingSenderId: '999477299207',
    projectId: 'connect-call-e0fc2',
    storageBucket: 'connect-call-e0fc2.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC20ciN4QE33c6KUQ7XQphkAZnTOBlGp4I',
    appId: '1:999477299207:web:01ac0bff24c94ac05a82a2',
    messagingSenderId: '999477299207',
    projectId: 'connect-call-e0fc2',
    authDomain: 'connect-call-e0fc2.firebaseapp.com',
    storageBucket: 'connect-call-e0fc2.firebasestorage.app',
    measurementId: 'G-XPPQDY1XHD',
  );
}
